/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: phYc+qQSRP9NAyKluYZ0Q+84wc/lDImXdTTohRaV/s/+ZdZiy5AVMkBhLVd/cwk72TcBA6OXYPGdt+S5gDgr/Q==
 */

// tslint:disable

type UserRole = 'admin' | 'moderator' | 'sysadmin' | 'user';
export type { UserRole };
