/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: NJzR9Hk5EiSj7Kfe3EJEcxggHQAc9S/LTniw/uCW419/SoS9WzhB7twc/7Rf7TZqCXLzkvDa2A23GuIOx09+wA==
 */

import ActivityCategories from './activity_categories';
import Users from './users';

interface Activity {
  category_id: ActivityCategories['id'];
  /**
   * @default CURRENT_TIMESTAMP
   */
  created: Date;
  created_by: Users['id'];
  description: string;
  /**
   * @default uuid_generate_v4()
   */
  id: string & { readonly __brand?: 'activity_id' };
  last_updated_by: Users['id'];
  name: string;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated: Date;
}
export default Activity;

interface Activity_InsertParameters {
  category_id: ActivityCategories['id'];
  /**
   * @default CURRENT_TIMESTAMP
   */
  created?: Date;
  created_by: Users['id'];
  description: string;
  /**
   * @default uuid_generate_v4()
   */
  id?: string & { readonly __brand?: 'activity_id' };
  last_updated_by: Users['id'];
  name: string;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated?: Date;
}
export type { Activity_InsertParameters };
