/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 9nPvgsuIqLqoVQvzoRRKV27t/jI/R+xk7jxEffH9uWx8XJvDohoFjpaFK72a+A8+HTPwuu8Wf44KPNiqD87XRA==
 */

import Users from './users';

interface ResetPasswordCodes {
  code: string & { readonly __brand?: 'reset_password_codes_code' };
  created_by: Users['id'] | null;
  /**
   * @default CURRENT_TIMESTAMP
   */
  generated: Date;
  user_id: Users['id'];
}
export default ResetPasswordCodes;

interface ResetPasswordCodes_InsertParameters {
  code: string & { readonly __brand?: 'reset_password_codes_code' };
  created_by?: Users['id'] | null;
  /**
   * @default CURRENT_TIMESTAMP
   */
  generated?: Date;
  user_id: Users['id'];
}
export type { ResetPasswordCodes_InsertParameters };
