/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5t99n4vuQhXdUiFhVS0bydOcIZdPr5Ygl50W9chv4yN/ZIZ0bidRM7jqQMsIhwrgUsocc4/GcShhOLK7YKFRjw==
 */

// tslint:disable

import Users from './users';

interface ResetPasswordCodes {
  code: string & { readonly __brand?: 'reset_password_codes_code' };
  /**
   * @default CURRENT_TIMESTAMP
   */
  generated: Date;
  user_id: Users['id'];
}
export default ResetPasswordCodes;

interface ResetPasswordCodes_InsertParameters {
  code: string & { readonly __brand?: 'reset_password_codes_code' };
  /**
   * @default CURRENT_TIMESTAMP
   */
  generated?: Date;
  user_id: Users['id'];
}
export type { ResetPasswordCodes_InsertParameters };
