/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 37BcMsTDbbFFdazjQYZTPorlZOcv1Am8Vwy+B5jOnUA8z38KDfgEzQk3NWLoKL+PdecqFTPrc1+zqJ0xRFOiKg==
 */

// tslint:disable

import { UserRole } from './_enums';

interface Users {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created: Date;
  email: string;
  /**
   * @default false
   */
  email_verified: boolean | null;
  /**
   * @default uuid_generate_v4()
   */
  id: string & { readonly __brand?: 'users_id' };
  language: string;
  name: string | null;
  password: string;
  refresh_hash: string | null;
  role: UserRole;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated: Date;
}
export default Users;

interface Users_InsertParameters {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created?: Date;
  email: string;
  /**
   * @default false
   */
  email_verified?: boolean | null;
  /**
   * @default uuid_generate_v4()
   */
  id?: string & { readonly __brand?: 'users_id' };
  language: string;
  name?: string | null;
  password: string;
  refresh_hash?: string | null;
  role: UserRole;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated?: Date;
}
export type { Users_InsertParameters };
