/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: euv2JQdJQd6y2uyAi3YQvHHANHyOWP3s/7cj4IMJaCmTjEjQmv+jBV6j2PqlDPEZqBLj3v+6L9org0QETtkcow==
 */

// tslint:disable

import Users from './users';

interface UserLocations {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created: Date;
  /**
   * @default uuid_generate_v4()
   */
  id: string & { readonly __brand?: 'user_locations_id' };
  location: string;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated: Date;
  user_id: Users['id'];
}
export default UserLocations;

interface UserLocations_InsertParameters {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created?: Date;
  /**
   * @default uuid_generate_v4()
   */
  id?: string & { readonly __brand?: 'user_locations_id' };
  location: string;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated?: Date;
  user_id: Users['id'];
}
export type { UserLocations_InsertParameters };
