/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: lfL6EEzXYDGtjN2/CcW2Wqv+ERjuQF/9Uw730ZdH0RZONu7f5QpX3RKonzIIfXJs5qCU1Mtda5dB1h0NMc8MiA==
 */

// tslint:disable

interface Users {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created: Date;
  email: string;
  /**
   * @default false
   */
  email_verified: boolean | null;
  /**
   * @default uuid_generate_v4()
   */
  id: string & { readonly __brand?: 'users_id' };
  language: string;
  name: string | null;
  password: string;
  refresh_hash: string | null;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated: Date;
}
export default Users;

interface Users_InsertParameters {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created?: Date;
  email: string;
  /**
   * @default false
   */
  email_verified?: boolean | null;
  /**
   * @default uuid_generate_v4()
   */
  id?: string & { readonly __brand?: 'users_id' };
  language: string;
  name?: string | null;
  password: string;
  refresh_hash?: string | null;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated?: Date;
}
export type { Users_InsertParameters };
