/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: yRj8HDqmuOQ2TY5RuWabRCvd+wj7NE3+wBZedUHxAycL54cifpP8tSQQ96uGNZtqZ8Fya88u7wFi7UCEx4fHmA==
 */

import { UserRole } from './_enums';

interface Users {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created: Date;
  created_by: string | null;
  email: string;
  /**
   * @default false
   */
  email_verified: boolean | null;
  /**
   * @default uuid_generate_v4()
   */
  id: string & { readonly __brand?: 'users_id' };
  language: string;
  last_updated_by: string | null;
  name: string | null;
  password: string;
  refresh_hash: string | null;
  role: UserRole;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated: Date;
}
export default Users;

interface Users_InsertParameters {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created?: Date;
  created_by?: string | null;
  email: string;
  /**
   * @default false
   */
  email_verified?: boolean | null;
  /**
   * @default uuid_generate_v4()
   */
  id?: string & { readonly __brand?: 'users_id' };
  language: string;
  last_updated_by?: string | null;
  name?: string | null;
  password: string;
  refresh_hash?: string | null;
  role: UserRole;
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated?: Date;
}
export type { Users_InsertParameters };
