name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set node version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      # - name: Cache node modules
      #   id: cache-npm
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     # npm cache files are stored in `~/.npm` on Linux/macOS
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      # - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      #   name: List the state of node modules
      #   continue-on-error: true
      #   run: npm list

      - name: Install dependencies
        run: npm install

      - name: Run pre-build
        run: yarn pre-build

      - name: Lint the code
        run: yarn nx run-many --target=lint --all
      - name: Run the tests
        # run: yarn nx run-many --target=test --all --coverage --coverageReporters=lcov,text --runInBand
        run: yarn nx run api:test --test-file=auth.controller.spec.ts --coverage=true --coverageReporters=lcov,text --runInBand=true
        env:
          MAIL_VERIFICATION_EXPIRY_HOURS: 1
          MAIL_VERIFICATION_RETRY_MINUTES: 1
          PASSWORD_RESET_EXPIRY_HOURS: 1
          FRONTEND_URL: http://localhost:4300
          ADMIN_URL: http://localhost:4600
          DEFAULT_SYSADMIN_EMAIL: ben@qntm.co.uk
          DEFAULT_SYSADMIN_NAME: Ben Meyrick

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
