name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set node version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run pre-build
        run: yarn pre-build

      - name: Lint the code
        run: yarn nx run-many --target=lint --all
      - name: Run the tests
        run: yarn nx run-many --target=test --all --coverage --coverageReporters=lcov,text
        env:
          MAIL_VERIFICATION_EXPIRY_HOURS: 1
          MAIL_VERIFICATION_RETRY_MINUTES: 1
          PASSWORD_RESET_EXPIRY_HOURS: 1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
